CREATE DATABASE IF NOT EXISTS users_db;
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE ON users_db.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
